<h1 id="title"><?php echo $this->translate('Feedback Form 2000!'); ?></h1>

<div id="menu">

    <div>
        <ul>
            <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'feedback')); ?>"><?php echo $this->translate('Leave Feedback'); ?></a></li>
            <li><a href="<?php echo $this->url(array(), 'view-feedback'); ?>"><?php echo $this->translate('View Feedback'); ?></a></li>
            <li><a href="<?php echo $this->url(array(), 'view-feedback-paged'); ?>"><?php echo $this->translate('View Feedback Paged'); ?></a></li>
            <li><a href="<?php echo $this->url(array(), 'crunch-data'); ?>"><?php echo $this->translate('Crunch Data'); ?></a></li>
            <li><a href="<?php echo $this->url(array(), 'help'); ?>"><?php echo $this->translate('Help'); ?></a></li>
        </ul>
    </div>
</div>

<p id="copyright">&copy;1999</p>