<h1><?php echo $this->translate('View Feedback'); ?></h1>

<table>
    
    <tr>
        <th><?php echo $this->translate('id'); ?></th>
        <th><?php echo $this->translate('Name'); ?></th>
        <th><?php echo $this->translate('Email'); ?></th>
        <th><?php echo $this->translate('Topic'); ?></th>
        <th><?php echo $this->translate('Feeling'); ?></th>
        <th><?php echo $this->translate('Feedback'); ?></th>
    </tr>
    
    <?php foreach ($this->feedbackEntries as $feedbackEntry): ?>
        <tr class="<?php echo $this->cycle(array('odd', 'even'))->next(); ?>">
            <td><?php echo $this->escape($feedbackEntry['id']); ?></td>
            <td><?php echo $this->escape($feedbackEntry['name']); ?></td>
            <td><?php echo $this->escape($feedbackEntry['email']); ?></td>
            <td><?php echo $this->escape($feedbackEntry['topic']); ?></td>
            <td><?php echo $this->escape($feedbackEntry['feeling']); ?></td>
            <td><?php echo $this->escape($feedbackEntry['feedback']); ?></td>            
        </tr>
    <?php endforeach; ?>
    
</table>