<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <?php echo $this->headMeta(); ?>        
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>
    </head>

	<body>

        <div id="top-menu">
            <a href="/"><?php echo $this->translate('Home'); ?></a>
            <a href="<?php echo $this->url(array('action' => 'switch-language', 'controller' => 'index'), 'default'); ?>"><?php echo $this->translate('Change Language'); ?></a>
            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'clear-cache'), 'default'); ?>"><?php echo $this->translate('Clear Cache'); ?></a>
        </div>

        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>

    </body>

</html>